spring:
  # Security OAuth
  security:
    oauth2.client:
      registration:
        google:
          clientId: 1099044816957-99f7op5g60g7ne2f8qckvau3pj8dsvel.apps.googleusercontent.com
          clientSecret: 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
          scope:
            - email
            - profile
